'use strict';

const mongoose = require('mongoose');

// ─── Status enum values ───────────────────────────────────────────────────────
const APPOINTMENT_STATUSES = [
  'awaiting_payment',   // slot locked, user is on payment page (30 min TTL)
  'pending_approval',   // screenshot submitted, admin must review
  'confirmed',          // admin approved payment
  'completed',          // doctor marked the appointment complete
  'cancelled',          // cancelled by user or admin
  'payment_rejected',   // admin rejected the screenshot
  'expired',            // lock expired before screenshot was submitted
  'rescheduled',        // this appointment replaced by a new one
  'no_show',            // user did not attend confirmed appointment
];

// ─── Appointment Schema ───────────────────────────────────────────────────────
const appointmentSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User reference is required.'],
    },
    appointmentDate: {
      type: Date,
      required: [true, 'Appointment date is required.'],
    },
    slotStart: {
      type: String,
      required: [true, 'Slot start time is required.'],
      match: [/^\d{2}:\d{2}$/, 'Slot start must be in HH:mm format.'],
    },
    slotEnd: {
      type: String,
      required: [true, 'Slot end time is required.'],
      match: [/^\d{2}:\d{2}$/, 'Slot end must be in HH:mm format.'],
    },
    consultationType: {
      type: String,
      required: [true, 'Consultation type is required.'],
      enum: {
        values: ['online', 'clinic'],
        message: "Consultation type must be 'online' or 'clinic'.",
      },
    },
    status: {
      type: String,
      enum: {
        values: APPOINTMENT_STATUSES,
        message: 'Invalid appointment status.',
      },
      default: 'awaiting_payment',
    },

    // ── Fee snapshot ─────────────────────────────────────────────────────────
    // Captured at booking time from DoctorProfile.consultationFee.
    // NEVER recalculate. NEVER change after creation.
    feeSnapshot: {
      type: Number,
      required: [true, 'Fee snapshot is required.'],
      min: [0, 'Fee cannot be negative.'],
    },

    // ── Payment ───────────────────────────────────────────────────────────────
    paymentSubmission: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'PaymentSubmission',
      default: null,
    },

    // ── Slot lock ─────────────────────────────────────────────────────────────
    // Set to Date.now() + 30 minutes on creation.
    // Cleared (set to null) once screenshot is submitted.
    // Cleanup job polls for expired locks every 5 minutes.
    lockedUntil: {
      type: Date,
      default: null,
    },

    // ── Online consultation join link ─────────────────────────────────────────
    // WhatsApp deep link generated by admin approval for online type.
    whatsappJoinLink: {
      type: String,
      default: null,
    },

    // ── Cancellation ──────────────────────────────────────────────────────────
    cancellationReason: { type: String, trim: true, default: null },
    cancelledBy: {
      type: String,
      enum: { values: ['user', 'admin', null], message: 'cancelledBy must be user or admin.' },
      default: null,
    },

    // ── Rescheduling ──────────────────────────────────────────────────────────
    rescheduledFrom: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Appointment',
      default: null,
    },

    // ── Admin metadata ────────────────────────────────────────────────────────
    adminNotes: { type: String, trim: true, default: null },

    // ── Reminder tracking ─────────────────────────────────────────────────────
    reminderSent: { type: Boolean, default: false },

    // ── Patient details snapshot (captured at booking time) ───────────────────
    // Stored so admin can see details even if user edits their profile later
    patientName: { type: String, trim: true },
    patientPhone: { type: String, trim: true },
    patientEmail: { type: String, trim: true, lowercase: true },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────

// CRITICAL: Compound partial index — prevents double-booking.
// Only active appointments (awaiting_payment/pending_approval/confirmed)
// block a slot. Other statuses are excluded from this index.
appointmentSchema.index(
  { appointmentDate: 1, slotStart: 1, consultationType: 1 },
  {
    unique: true,
    partialFilterExpression: {
      status: { $in: ['awaiting_payment', 'pending_approval', 'confirmed'] },
    },
    name: 'unique_active_slot',
  }
);

// User's appointment list (sorted newest first)
appointmentSchema.index({ user: 1, createdAt: -1 });

// Admin panel: filter by status + date range
appointmentSchema.index({ status: 1, appointmentDate: -1 });

// Cleanup job query: find expired locks
appointmentSchema.index({ status: 1, lockedUntil: 1 });

// Date-based queries for availability algorithm
appointmentSchema.index({ appointmentDate: 1, status: 1 });

// ─── Pre-save: Normalize appointmentDate to UTC midnight ─────────────────────
appointmentSchema.pre('save', function () {
  if (this.appointmentDate && this.isModified('appointmentDate')) {
    const d = new Date(this.appointmentDate);
    this.appointmentDate = new Date(
      Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate())
    );
  }
});

// ─── Virtuals ─────────────────────────────────────────────────────────────────
appointmentSchema.virtual('isLockExpired').get(function () {
  if (!this.lockedUntil) return false;
  return new Date() > this.lockedUntil;
});

appointmentSchema.virtual('lockRemainingSeconds').get(function () {
  if (!this.lockedUntil) return 0;
  const remaining = Math.floor((this.lockedUntil - new Date()) / 1000);
  return Math.max(0, remaining);
});

// ─── Static: Get currently booked slot strings for a date ────────────────────
// Returns an array of slotStart strings that are currently blocked.
appointmentSchema.statics.getBlockedSlots = async function (
  appointmentDate,
  consultationType
) {
  const d = new Date(appointmentDate);
  const dayStart = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  const dayEnd = new Date(dayStart.getTime() + 24 * 60 * 60 * 1000);

  const now = new Date();

  // Build the query: status must block the slot
  const query = {
    appointmentDate: { $gte: dayStart, $lt: dayEnd },
    $or: [
      { status: 'pending_approval' },
      { status: 'confirmed' },
      {
        status: 'awaiting_payment',
        lockedUntil: { $gt: now }, // only non-expired locks
      },
    ],
  };

  // Since there is a single doctor, any active booking of either type blocks the slot globally.

  const appointments = await this.find(query).select('slotStart').lean();
  return appointments.map((a) => a.slotStart);
};

const Appointment = mongoose.model('Appointment', appointmentSchema);
module.exports = Appointment;
